/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsKavalRouteImport } from './routes/products.kaval'
import { Route as ProductsHadiRouteImport } from './routes/products.hadi'
import { Route as ProductsKavalIndexRouteImport } from './routes/products.kaval.index'
import { Route as ProductsHadiIndexRouteImport } from './routes/products.hadi.index'
import { Route as ProductsKavalPrivacyRouteImport } from './routes/products.kaval.privacy'
import { Route as ProductsHadiPrivacyRouteImport } from './routes/products.hadi.privacy'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsKavalRoute = ProductsKavalRouteImport.update({
  id: '/products/kaval',
  path: '/products/kaval',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHadiRoute = ProductsHadiRouteImport.update({
  id: '/products/hadi',
  path: '/products/hadi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsKavalIndexRoute = ProductsKavalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsKavalRoute,
} as any)
const ProductsHadiIndexRoute = ProductsHadiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsHadiRoute,
} as any)
const ProductsKavalPrivacyRoute = ProductsKavalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProductsKavalRoute,
} as any)
const ProductsHadiPrivacyRoute = ProductsHadiPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProductsHadiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/products/hadi': typeof ProductsHadiRouteWithChildren
  '/products/kaval': typeof ProductsKavalRouteWithChildren
  '/products/hadi/privacy': typeof ProductsHadiPrivacyRoute
  '/products/kaval/privacy': typeof ProductsKavalPrivacyRoute
  '/products/hadi/': typeof ProductsHadiIndexRoute
  '/products/kaval/': typeof ProductsKavalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/products/hadi/privacy': typeof ProductsHadiPrivacyRoute
  '/products/kaval/privacy': typeof ProductsKavalPrivacyRoute
  '/products/hadi': typeof ProductsHadiIndexRoute
  '/products/kaval': typeof ProductsKavalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/products/hadi': typeof ProductsHadiRouteWithChildren
  '/products/kaval': typeof ProductsKavalRouteWithChildren
  '/products/hadi/privacy': typeof ProductsHadiPrivacyRoute
  '/products/kaval/privacy': typeof ProductsKavalPrivacyRoute
  '/products/hadi/': typeof ProductsHadiIndexRoute
  '/products/kaval/': typeof ProductsKavalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/products/hadi'
    | '/products/kaval'
    | '/products/hadi/privacy'
    | '/products/kaval/privacy'
    | '/products/hadi/'
    | '/products/kaval/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/products/hadi/privacy'
    | '/products/kaval/privacy'
    | '/products/hadi'
    | '/products/kaval'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/products/hadi'
    | '/products/kaval'
    | '/products/hadi/privacy'
    | '/products/kaval/privacy'
    | '/products/hadi/'
    | '/products/kaval/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsHadiRoute: typeof ProductsHadiRouteWithChildren
  ProductsKavalRoute: typeof ProductsKavalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/kaval': {
      id: '/products/kaval'
      path: '/products/kaval'
      fullPath: '/products/kaval'
      preLoaderRoute: typeof ProductsKavalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hadi': {
      id: '/products/hadi'
      path: '/products/hadi'
      fullPath: '/products/hadi'
      preLoaderRoute: typeof ProductsHadiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/kaval/': {
      id: '/products/kaval/'
      path: '/'
      fullPath: '/products/kaval/'
      preLoaderRoute: typeof ProductsKavalIndexRouteImport
      parentRoute: typeof ProductsKavalRoute
    }
    '/products/hadi/': {
      id: '/products/hadi/'
      path: '/'
      fullPath: '/products/hadi/'
      preLoaderRoute: typeof ProductsHadiIndexRouteImport
      parentRoute: typeof ProductsHadiRoute
    }
    '/products/kaval/privacy': {
      id: '/products/kaval/privacy'
      path: '/privacy'
      fullPath: '/products/kaval/privacy'
      preLoaderRoute: typeof ProductsKavalPrivacyRouteImport
      parentRoute: typeof ProductsKavalRoute
    }
    '/products/hadi/privacy': {
      id: '/products/hadi/privacy'
      path: '/privacy'
      fullPath: '/products/hadi/privacy'
      preLoaderRoute: typeof ProductsHadiPrivacyRouteImport
      parentRoute: typeof ProductsHadiRoute
    }
  }
}

interface ProductsHadiRouteChildren {
  ProductsHadiPrivacyRoute: typeof ProductsHadiPrivacyRoute
  ProductsHadiIndexRoute: typeof ProductsHadiIndexRoute
}

const ProductsHadiRouteChildren: ProductsHadiRouteChildren = {
  ProductsHadiPrivacyRoute: ProductsHadiPrivacyRoute,
  ProductsHadiIndexRoute: ProductsHadiIndexRoute,
}

const ProductsHadiRouteWithChildren = ProductsHadiRoute._addFileChildren(
  ProductsHadiRouteChildren,
)

interface ProductsKavalRouteChildren {
  ProductsKavalPrivacyRoute: typeof ProductsKavalPrivacyRoute
  ProductsKavalIndexRoute: typeof ProductsKavalIndexRoute
}

const ProductsKavalRouteChildren: ProductsKavalRouteChildren = {
  ProductsKavalPrivacyRoute: ProductsKavalPrivacyRoute,
  ProductsKavalIndexRoute: ProductsKavalIndexRoute,
}

const ProductsKavalRouteWithChildren = ProductsKavalRoute._addFileChildren(
  ProductsKavalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsHadiRoute: ProductsHadiRouteWithChildren,
  ProductsKavalRoute: ProductsKavalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
